# Generated by Django 4.1.3 on 2022-12-23 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcategories', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MenuTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(max_length=300)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeekaki.menucategories')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitem', models.CharField(max_length=300)),
                ('midescription', models.CharField(max_length=300)),
                ('miprice', models.FloatField(max_length=300)),
                ('miphoto', models.CharField(max_length=300)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeekaki.menutypes')),
            ],
        ),
    ]
