# Generated by Django 4.1.3 on 2022-12-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeekaki', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuCategories',
            new_name='MenuCategorie',
        ),
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='MenuItem',
        ),
        migrations.RenameModel(
            old_name='MenuTypes',
            new_name='MenuType',
        ),
    ]
