# Generated by Django 4.1.3 on 2022-12-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeekaki', '0002_rename_menucategories_menucategorie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menucategorie',
            old_name='mcategories',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='midescription',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='tid',
            new_name='menu_type',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='miprice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='menutype',
            old_name='cid',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='menutype',
            old_name='mtype',
            new_name='menu_type',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='miphoto',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='mitem',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='photo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
