# Generated by Django 4.1.3 on 2022-12-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeekaki', '0005_product_catergory_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catergory',
            new_name='category',
        ),
    ]
