# Generated by Django 4.1.3 on 2022-12-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeekaki', '0010_alter_product_description_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['number_of_sales', 'category', 'type']},
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_sales',
            field=models.IntegerField(default=0),
        ),
    ]
