# Generated by Django 4.1.3 on 2022-12-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeekaki', '0011_alter_product_options_product_number_of_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-number_of_sales', 'category', 'type']},
        ),
    ]
