# Generated by Django 4.1.3 on 2023-01-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeekaki', '0016_alter_customer_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
