# Generated by Django 4.1.3 on 2023-01-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeekaki', '0022_rename_user_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
