# Generated by Django 4.1.3 on 2023-01-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeekaki', '0026_orderitem_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_history', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_ordered']},
        ),
    ]
