# Generated by Django 4.1.3 on 2023-01-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeekaki', '0027_state_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
