# Generated by Django 4.1.3 on 2023-01-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeekaki', '0028_state_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='show_history',
            new_name='state',
        ),
    ]
