# Generated by Django 4.1.4 on 2023-02-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeekaki', '0030_orderitem_table_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-date_added']},
        ),
    ]
